atgaccagcatagctgtaaagtcgaaaaaagggcaaaacatcagccgcgcatccccgttg
ggcgtttgtccacactcatggttgtgttaccgatttagtcgacggaggaaatgtgccgct
ctcatctccaagagggggcctaacgtcagagacgtctcgggaggtaaagcatcgtatatg
cggggttcggtctcgtactgccgccggccatgcacgcgcgttattatgggacctcgaggg
gatgtcccacggctcgtgcgcaccagtccgcggtgtttcattgacgctgctatgtcctaa
